In [9]:
import numpy as np

rng = np.random.RandomState(57)
X = rng.randint(0, 10, (5,4))
y = np.array([2,0,2,1,1])
#print(X)
#print(y)
#print('\n')
k=5
data = 4
i=0
print(X)
y_pred = np.zeros(data)
for i in range(data):
    closest_y = []
    
    for a in range(k):
        position_closest_neighbor = np.argsort(X, axis=1)[i,a:a+1]
        print('the closest neigbohr is in  position:' , position_closest_neighbor)
        closest_y.append(int(y[position_closest_neighbor]))
        print('and has the label',closest_y)
        print('\n')
    
    y_pred[i]=max(closest_y,key=closest_y.count)




[[6 5 6 8]
 [2 8 8 1]
 [7 9 5 8]
 [8 1 1 2]
 [0 1 6 4]]
the closest neigbohr is in  position: [1]
and has the label [0]


the closest neigbohr is in  position: [0]
and has the label [0, 2]


the closest neigbohr is in  position: [2]
and has the label [0, 2, 2]


the closest neigbohr is in  position: [3]
and has the label [0, 2, 2, 1]


the closest neigbohr is in  position: []


TypeError: only size-1 arrays can be converted to Python scalars